"""Added email, password, and id to users

Revision ID: 4684e4631ebb
Revises: 7d225675e312
Create Date: 2025-10-15 22:51:55.839376

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4684e4631ebb"
down_revision: Union[str, Sequence[str], None] = "7d225675e312"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "id", sa.Integer(), nullable=False, primary_key=True, autoincrement=True
        ),
    )
    # Create users and passwords columns with placeholder values to allow them to be un-nullable and also unique
    op.add_column(
        "users", sa.Column("email", sa.String(), nullable=False, server_default="temp")
    )
    op.add_column(
        "users",
        sa.Column("password", sa.String(), nullable=False, server_default="temp"),
    )
    op.execute("UPDATE users SET email = 'temp-email-' || id")
    op.execute("UPDATE users SET password = 'temp-password-' || id")

    op.create_unique_constraint(None, "users", ["email"])
    op.create_unique_constraint(None, "users", ["name"])
    op.alter_column("users", "email", server_default=None)
    op.alter_column("users", "password", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "password")
    op.drop_column("users", "email")
    op.drop_column("users", "id")
    # ### end Alembic commands ###
